service: serverless-esbuild-issues

## Uncomment below for manual bundling with esbuild
# package:
#   artifact: artifacts/lambda.zip

## Uncomment below for serverless esbuild scenario
build:
  esbuild:
    bundle: true
    target: es2020
    platform: node
    sourcemap:
      type: linked
      setNodeOptions: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  runtime: nodejs22.x
  logs:
    lambda:
      logFormat: JSON

functions:
  user:
    handler: src/index.handle
    events:
      - httpApi:
          path: /
          method: get
